### ISSUE TITLE
INGRID crashes at launch

### ISSUE THREAD

**Issue by mikekryjak** [LLNL/INGRID#14]
Hi everyone. I've downloaded and installed the latest master based on the very helpful instructions in the [documentation](https://ingrid.readthedocs.io/en/latest/installation.html). I tried to launch INGRID from the `drivers` directory:
```
python StartGUI.py
```

and I have also tried to launch it from an import:
```
from INGRID import ingrid
ingrid.QuickStart()
```

Both result in the below error:
```
Traceback (most recent call last):
  File "C:\Users\mikek\OneDrive\Project\python-packages\INGRID\drivers\StartGUI.py", line 3, in <module>
    IG.QuickStart()
  File "C:\Users\mikek\AppData\Roaming\Python\Python310\site-packages\ingrid-2.0.0-py3.10.egg\INGRID\ingrid.py", line 57, in QuickStart
    QuickGrid.StartGUI()
  File "C:\Users\mikek\AppData\Roaming\Python\Python310\site-packages\ingrid-2.0.0-py3.10.egg\INGRID\ingrid.py", line 157, in StartGUI
    self.IngridWindow = IngridGUI(IngridSession=self)
  File "C:\Users\mikek\AppData\Roaming\Python\Python310\site-packages\ingrid-2.0.0-py3.10.egg\INGRID\gui\ingrid_gui.py", line 54, in __init__
    self.PopulateGUI()
  File "C:\Users\mikek\AppData\Roaming\Python\Python310\site-packages\ingrid-2.0.0-py3.10.egg\INGRID\gui\ingrid_gui.py", line 115, in PopulateGUI
    frame = F(self.container, self)
  File "C:\Users\mikek\AppData\Roaming\Python\Python310\site-packages\ingrid-2.0.0-py3.10.egg\INGRID\gui\ingrid_gui.py", line 123, in __init__
    tk.Frame.__init__(self, parent)
  File "C:\Users\mikek\anaconda3\envs\ingrid\lib\tkinter\__init__.py", line 3163, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "C:\Users\mikek\anaconda3\envs\ingrid\lib\tkinter\__init__.py", line 2595, in __init__
    self._setup(master, cnf)
  File "C:\Users\mikek\anaconda3\envs\ingrid\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  File "C:\Users\mikek\anaconda3\envs\ingrid\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  File "C:\Users\mikek\anaconda3\envs\ingrid\lib\tkinter\__init__.py", line 2383, in __getattr__
    return getattr(self.tk, attr)
  [Previous line repeated 987 more times]
RecursionError: maximum recursion depth exceeded
```

The error seems related to Tkinter, see https://stackoverflow.com/questions/10039485/tkinter-runtimeerror-maximum-recursion-depth-exceeded.

**Comment by bryan-garcia** [comment]
Apologies for the delay on this. Do you happen to have the environment on hand that caused this issue? If so, could you provide a pip freeze report of your package versions? 

I just took a stab at this with a fresh build one of the LC machines and I was able to boot up the GUI successfully. It's been some time since we've looked into dependencies, so this will also be helpful for updating our requirements.

**Comment by mikekryjak** [comment]
Hi @bryan-garcia! Apologies, unfortunately I have since had to get rid of conda, get rid of all my environments and start again with a different environment manager. Pretty sure it was a fresh Python 3.10 conda environment on Windows with no packages at all apart from what I installed by running `python setup.py install --user`. Unfortunately I will need to reinstall conda and recreate the environment to reproduce the problem, unless there is a way to install it with `pyenvs`.

It's interesting that you can't reproduce the issue - Maxim Umansky (LLNL) and Mike Wigram (MIT) both reported getting the same problem as me, so it does sound like a potentially subtle dependency incompatibility.
I'll try to reproduce the issue in the next few days.

**Comment by holm10** [comment]
Able to reproduce error. System and software information:
- macOS 12.6.7
- M1 Pro chip
- Reproduced Tkinter versions 23.3.1 and 23.7.3
- venv pip packages
  - contourpy==1.1.0
  - cycler==0.11.0
  - fonttools==4.42.1
  - kiwisolver==1.4.5
  - matplotlib==3.7.2
  - numpy==1.25.2packaging==23.1
Pillow==10.0.0
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0.1
scipy==1.11.2
six==1.16.0

**Comment by jguterl** [comment]
Use python=3.8 to get the right tinker version

**Comment by umansky** [comment]
I can reproduce the bug on my Mac using python 3.10. -Maxim-


From: Jerome Guterl ***@***.***>
Date: Thursday, September 7, 2023 at 2:06 PM
To: LLNL/INGRID ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [LLNL/INGRID] INGRID crashes at launch (Issue #14)
Use python=3.8 to get the right tinker version

**Comment by bryan-garcia** [comment]
> Use python=3.8 to get the right tinker version

Thanks for this solution, @jguterl. I was able to get the GUI working on Windows using python 3.8. 

Do you happen have some more information on what happened on the tkinter side with python >3.8?  It'd be nice to know how to support users with newer python versions.

**Comment by bryan-garcia** [comment]
@mikekryjak , we've merged a solution into master that resolved the crashing bug on Windows using python > 3.9. Maxim and Andreas have also had their issues resolved on macOS.
